/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.PointerInfo;
import javax.swing.JTextField;
import modelo.Registro;

/**
 *
 * @author ycgc
 */
public class VistaRegistro extends javax.swing.JFrame {

    private ControladorVistaRegistro controlador;
    /**
     * Creates new form RegistroJFrame
     */
    public VistaRegistro() {
        initComponents();
        controlador=new ControladorVistaRegistro(this);
        vistaTemperaturas = new VistaTemperaturas();
        vistaTemperaturas.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmaRegistroJDialog = new javax.swing.JDialog();
        preguntaConfirmaciónJLabel = new javax.swing.JLabel();
        confirmaJButton = new javax.swing.JButton();
        cancelaJButton = new javax.swing.JButton();
        introduzcaTemperaturaJLabel = new javax.swing.JLabel();
        nuevaTemperaturaJTextField = new javax.swing.JTextField();
        registraNuevaTemperaturaJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        title = new javax.swing.JLabel();

        confirmaRegistroJDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        preguntaConfirmaciónJLabel.setText("¿Está seguro de que quiere añadir esa temperatura?");

        confirmaJButton.setText("Sí");
        confirmaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaJButtonActionPerformed(evt);
            }
        });

        cancelaJButton.setText("No");
        cancelaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmaRegistroJDialogLayout = new javax.swing.GroupLayout(confirmaRegistroJDialog.getContentPane());
        confirmaRegistroJDialog.getContentPane().setLayout(confirmaRegistroJDialogLayout);
        confirmaRegistroJDialogLayout.setHorizontalGroup(
            confirmaRegistroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmaRegistroJDialogLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(preguntaConfirmaciónJLabel)
                .addGap(58, 58, 58))
            .addGroup(confirmaRegistroJDialogLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(confirmaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(cancelaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmaRegistroJDialogLayout.setVerticalGroup(
            confirmaRegistroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaRegistroJDialogLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(preguntaConfirmaciónJLabel)
                .addGap(33, 33, 33)
                .addGroup(confirmaRegistroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        introduzcaTemperaturaJLabel.setText("Introduzca temperatura:");

        nuevaTemperaturaJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevaTemperaturaJTextFieldMouseClicked(evt);
            }
        });
        nuevaTemperaturaJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaTemperaturaJTextFieldActionPerformed(evt);
            }
        });

        registraNuevaTemperaturaJButton.setText("Registra nueva temperatura");
        registraNuevaTemperaturaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraNuevaTemperaturaJButtonActionPerformed(evt);
            }
        });

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ºC", "ºF" }));

        title.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        title.setText("Registro de Temperaturas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(registraNuevaTemperaturaJButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(introduzcaTemperaturaJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nuevaTemperaturaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introduzcaTemperaturaJLabel)
                    .addComponent(nuevaTemperaturaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registraNuevaTemperaturaJButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registraNuevaTemperaturaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraNuevaTemperaturaJButtonActionPerformed
        controlador.comprobarTemperatura(getTemp(), "ºC".equals((String)jComboBoxType.getSelectedItem()));
        
        
    }//GEN-LAST:event_registraNuevaTemperaturaJButtonActionPerformed

    private void nuevaTemperaturaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaTemperaturaJTextFieldActionPerformed
        
        
    }//GEN-LAST:event_nuevaTemperaturaJTextFieldActionPerformed

    private void nuevaTemperaturaJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaTemperaturaJTextFieldMouseClicked
        nuevaTemperaturaJTextField.setText("");
        nuevaTemperaturaJTextField.setBackground(Color.WHITE);
    }//GEN-LAST:event_nuevaTemperaturaJTextFieldMouseClicked

    private void cancelaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaJButtonActionPerformed
        controlador.noGuardarTemperatura();
    }//GEN-LAST:event_cancelaJButtonActionPerformed

    private void confirmaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaJButtonActionPerformed
        controlador.guardarTemperatura();
    }//GEN-LAST:event_confirmaJButtonActionPerformed

    public String getTemp() {
        return nuevaTemperaturaJTextField.getText();
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelaJButton;
    private javax.swing.JButton confirmaJButton;
    private javax.swing.JDialog confirmaRegistroJDialog;
    private javax.swing.JLabel introduzcaTemperaturaJLabel;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nuevaTemperaturaJTextField;
    private javax.swing.JLabel preguntaConfirmaciónJLabel;
    private javax.swing.JButton registraNuevaTemperaturaJButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private VistaTemperaturas vistaTemperaturas;
    
    public void muestraError() {
        nuevaTemperaturaJTextField.setBackground(Color.RED);
    }

    public void muestraConfirmacion() {
        confirmaRegistroJDialog.setLocationRelativeTo(this);
        confirmaRegistroJDialog.setVisible(true);
    }

    public void cerrarConfirmacion() {
        confirmaRegistroJDialog.setVisible(false);
    }

    public void muestraTemperaturas() {
        vistaTemperaturas.setVisible(true);
        vistaTemperaturas.setLocationRelativeTo(this);
        vistaTemperaturas.muestraTemperaturaMedia(Registro.getRegistro().getTemperaturaMedia());
        vistaTemperaturas.muestraTemperaturaMinima(Registro.getRegistro().getTemperaturaMinima());
        vistaTemperaturas.muestraTemperaturaMaxima(Registro.getRegistro().getTemperaturaMaxima());
    }
}
