/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import modelo.Temperatura;

/**
 *
 * @author ycgc
 */
public class VistaTemperaturas extends javax.swing.JDialog {

    private ControladorVistaTemperaturas controlador;
    /**
     * Creates new form TemperaturasJFrame
     */
    public VistaTemperaturas() {
        initComponents();
         controlador = new ControladorVistaTemperaturas(this);
         jLabelValorMedio.setText("no hay registro");
         jLabelValorMin.setText("no hay registro");
         jLabelValorMax.setText("no hay registro");
    }
    
    public void muestraTemperaturaMinima(Temperatura minima) {
        if (minima==null) {
            jLabelValorMin. setText("no hay registro");
        }
        else {
            jLabelValorMin.setText(minima.getValor() + " ");
        }
    }
    
    public void muestraTemperaturaMaxima(Temperatura maxima) {
        if (maxima==null) {
            jLabelValorMax. setText("no hay registro");
        }
        else {
            jLabelValorMax.setText(maxima.getValor() + " ");
        }
    }
    
    public void muestraTemperaturaMedia(Temperatura media) {
        if (media==null) {
            System.out.println("a");
            jLabelValorMedio.setText("no hay registro");
        }
        else {
            jLabelValorMedio.setText(media.getValor() + " ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTempMedia = new javax.swing.JLabel();
        jLabelTempMin = new javax.swing.JLabel();
        jLabelTempMax = new javax.swing.JLabel();
        jLabelValorMedio = new javax.swing.JLabel();
        jLabelValorMin = new javax.swing.JLabel();
        jLabelValorMax = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabelTempMedia.setText("Temperatura media:");

        jLabelTempMin.setText("Temperatura mínima:");

        jLabelTempMax.setText("Temperatura máxima:");

        jLabel7.setText("º C");

        jLabel8.setText("º C");

        jLabel9.setText("º C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTempMedia)
                    .addComponent(jLabelTempMin)
                    .addComponent(jLabelTempMax))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelValorMax)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelValorMin)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelValorMedio)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempMedia)
                    .addComponent(jLabelValorMedio)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempMin)
                    .addComponent(jLabelValorMin)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempMax)
                    .addComponent(jLabelValorMax)
                    .addComponent(jLabel9))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTempMax;
    private javax.swing.JLabel jLabelTempMedia;
    private javax.swing.JLabel jLabelTempMin;
    private javax.swing.JLabel jLabelValorMax;
    private javax.swing.JLabel jLabelValorMedio;
    private javax.swing.JLabel jLabelValorMin;
    // End of variables declaration//GEN-END:variables
}
